// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnpxquukrqpazqaobhed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucHhxdXVrcnFwYXpxYW9iaGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzM0NjksImV4cCI6MjA2MTAwOTQ2OX0.8sN8Tr8NlXZwUsf5mtYGy3prlnzChLzF6Tt0lWOHcmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);